version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8876:80"
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
    container_name: app_nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    user: 1000:1000
    depends_on:
      - postgres
    container_name: app

  postgres:
    image: postgres
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    container_name: postgres_db