version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - php
    container_name: app_nginx

  php:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    user: 1000:1000
    depends_on:
      - postgres
    container_name: php

  postgres:
    image: postgres
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    container_name: postgres